swagger: '2.0' 
info:
  description: "Wyvern Choice API"
  version: 1.0.0
  title: "Wyvern Choice API"
 # host: "24hdpfa774.execute-api.us-east-1.amazonaws.com"
schemes:
- "https"
paths:
  #delete stale choices
  #produce a list of choices
  #doesn't belong in any path though???
  /choice:
    ##create choice
    ##Also generate a link here?
    post_createChoice:
      operationId: "createChoice"
      description: "Creates a choice. Admin only"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
        400:
          description: "400 response"
      x-amazon-apigateway-integration:
        type: "aws"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:360474612808:function:adder/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
    ##user login (add user, database)
    post_userLogin:
      operationId: "userLogin"
      description: "User logs in. If this is their first time logging in, their name and optional password is added to the database."
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
        400: 
          description: "400 response"
    #name of choice
    get_getChoiceName:
      operationId: "getChoiceName"
      description: "Returns the name of the choice created by the admin"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
        400:
          description: "400 response"
      
    #name of poster
    get:
      operationId: "getChoiceCreator"
      description: "Gets the name of the admin who created the choice."
    #alternatives
    get:
      operationId: "getAlternatives"
      description: "Get the list of alternatives currently in the choice."
      
    get:
      operationId: "getSpecificAlternative"
      description: "Get a specific alternative within the choice."
      
    get:
      operationId: "deleteSpecificAlternative"
      description: "Delete a specific alternative within the choice."
      
    #picked alternative (if one is picked)
    get:
      operationId: "getFinalAlternative"
      description: "If an alternative was picked as the final decision, it is retrieved."
  /alternative:
    ##create alternative
    post:
      operationId: "createAlternative"
      description: "Create a new alternative within the choice."
      
    ##manually updoot
    post:
      operationId: "createUpvote"
      description: "Register an upvote request a user sends."
      
    ##manually downdoot
    post:
      operationId: "createDownvote"
      description: "Register a downvote request a user sends."
    
    ##manually unupdoot
    post:
      operationId: "removeUpvote"
      description: "Remove an upvote the user already made."
      
    ##manually undowndoot
    post:
      operationId: "removeDownvote"
      description: "Remove a downvote the user already made."
      
    ##make feedback
    post:
      operationId: "createFeedback"
      description: "Create a new piece of feedback that an individual desires to send."
    
    ##make a final choice
    post:
      operationId: "makeFinalChoice"
      description: "Allows for a user to mark an alternative as the final decision."
    
    #name of alternative
    get:
      operationId: "getAlternativeName"
      description: "Gets the name of the alternative."
    
    #feedback
    get:
      operationId: "getFeedback"
      description: "Gets a list of all the feedback sent from various users."
    
    #specific feedback
    get:
      operationId: "getSpecificFeedback"
      description: "Gets a specific line of feedback."
      
    #updoots
    get:
      operationId: "getUpvotes"
      description: "Get the total amount of upvotes for a given alternative"
      
    #downdoots
    get:
      operationId: "getDownvotes"
      description: "Get the total amount of downvotes for a given alternative"
      
    #upvote score
    get:
      operationId: "getApprovalScore"
      description: "Get the total score of upvotes and downvotes for a given alternative"
      
    #chosen alternative button
    get:
      operationId: "getIsFinalChoice"
      description: "If the final alternative has been decided, pick it from the list of alternatives"
      
  /feedback:
    #name of poster
    get:
      operationId: "getFeedbackCreator"
      description: "Get the name of the user who posted the feedback"
      
    #feedback text
    get:
      operationId: "getFeedbackText"
      description: "Get the written message of the feedback"
      
    #timestamp
    get:
      operationId: "getFeedbackTimestamp"
      description: "Get the timestamp at which the feedback was written"
definitions:
  ListOfChoices:
  Choice:
  ListofAlternatives:
  Alternative:
  ListofFeedback:
  Feedback:
  
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /justgaret23/cs3733wyvern/1.0.0